apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lemp_k8s_chart" . }}-nginx-config
  labels:
    {{- include "lemp_k8s_chart.labels" . | nindent 4 }}
data:
  {{ toYaml .Values.resMysql | indent 2 }}
