apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmlemp.fullname" . }}
  labels: {{- include "helmlemp.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.serviceMysql.port }}
  selector: {{- include "helmlemp.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helmlemp.fullname" . }}-mysql-pvc
  labels:
     {{- include "helmlemp.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.sizeMysql }}
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "helmlemp.fullname" . }}-mysql
  labels:
    {{- include "helmlemp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "helmlemp.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.strategy.type }}
  template:
    metadata:
      labels:
        {{- include "helmlemp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: "{{ .Values.imageTagMysql }}"
        name: mysql
        resources:
{{ toYaml .Values.resMysql.resources | indent 12 }}
        # env:
        # - name: MYSQL_ROOT_PASSWORD
        #   valueFrom:  
        #     secretKeyRef:
        #       name: mysql-pass
        #       key: password
        ports:
        - containerPort: {{ .Values.serviceMysql.port }}
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: {{ .Values.mysqlPath.mountPath }}
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ include "helmlemp.fullname" . }}-mysql-pvc
