apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helmlemp.fullname" . }}-nginx-pvc-volume
spec:
  accessModes:
  - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.sizeNginx }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helmlemp.fullname" . }}-nginx
  labels:
    {{- include "helmlemp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "helmlemp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "helmlemp.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: {{ include "helmlemp.fullname" . }}-nginx-pvc-volume
        persistentVolumeClaim:
          claimName: {{ include "helmlemp.fullname" . }}-nginx-pvc-volume
      - name: config
        configMap:
          name: nginx-config
          items:
          - key: config
            path: site.conf
      containers:
      - name: nginx
        image: "{{ .Values.imageTagWeb }}"
        resources:
  {{ toYaml .Values.resNginx | indent 10 }}
        volumeMounts:
        - name: {{ include "helmlemp.fullname" . }}-nginx-pvc-volume
          mountPath: {{ .Values.nginxPath.mountPath1}}
        - name: config
          mountPath: {{ .Values.nginxPath.mountPath2}}
---
apiVersion: v1
kind: Service
metadata:
  name:  {{ include "helmlemp.fullname" . }}
spec:
  selector:
    {{- include "helmlemp.selectorLabels" . | nindent 6 }}
  type: {{ .Values.serviceWeb.type }}
  ports:
    - port: {{ .Values.serviceWeb.port }}
