apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helmlemp.fullname" . }}-nginx-config
  labels:
    {{- include "helmlemp.labels" . | nindent 4 }}
data:
  {{ toYaml .Values.resMysql | indent 2 }}
