apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helmlemp.fullname" . }}-phpmyadmin
  labels:
    {{- include "helmlemp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "helmlemp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helmlemp.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: phpmyadmin
        emptyDir: {}
      - name: config
      containers:
      - name: phpmyadmin
        image: {{ .Values.imageTagPhpAdmin}}
        resources:
{{ toYaml .Values.resPhpAdmin.resources | indent 12 }}
        env:
        - name: PMA_HOST
          value: mysql-service  
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmlemp.fullname" . }}-phpmyadmin
spec:
  selector:
    {{- include "helmlemp.selectorLabels" . | nindent 6 }}
  type: {{ .Values.serviceWeb.type }}
  ports:
    - port: {{ .Values.serviceWeb.port }}
