apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "helmlemp.fullname" . }}-nginx-pv-volume
  labels:
    {{- include "helmlemp.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.sizeMysql | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  hostPath:
    path: "{{ .Values.pvPath.path2 }}"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "helmlemp.fullname" . }}-mysql-pv-volume
  labels:
    {{- include "helmlemp.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.sizeMysql | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  hostPath:
    path: "{{ .Values.pvPath.path2 }}"
