apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helmlemp.fullname" . }}-mysql-pass
type: Opaque
data:
  {{ if .Values.mysqlRootPassword }}
  password:  {{ .Values.mysqlRootPassword | b64enc | quote }}
  {{ else }}
  password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
